---
- name: Install postgres repo rhel 8
  ansible.builtin.dnf:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: present

- name: Install postges server and python package
  ansible.builtin.package:
    name: 
      - postgresql-"{{ postgres_version }}"
      - python3-psycopg2
      - pigz
    state: present

- name: deploy postgres.conf with tuning
  ansible.builtin.template:
    src: templates/postgresql.conf.j2
    dest: "{{ postgres_conf }}"
    owner: postgres
    group: postgres
    mode: '0644'

- name: Create postgres database wih encoding
  community.postgresql.postgresql_db:
    name: "{{ postgres_database }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
  become_user: postgres

- name: create postgres user give access database
  community.postgresql.postgresql_user:
    db: "{{ postgres_database }}"
    name: "{{ postgres_user }}"
    password: "{{ postgres_user_password }}"
    priv: ALL
    expires: infinity
    state: present
  become_user: postgres

- name: set postgres user access ip address and auth method
  community.postgresql.postgresql_pg_hba:
    dest: "/var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf"
    contype: host
    users: "{{ postgres_user }}"
    source: "{{ ip_address }}/{{ netmask }}"
    databases: "{{ postgres_database }}"
    method: "{{ postgres_auth_method }}"
    state: present
  become_user: postgres

- name: restart postgres servies so tuning can take effect
  ansible.builtin.systemd:
    name: postgresql
    enabled: yes
    state: restarted