---
- name: Install haproxy package
  ansible.builtin.package:
    name: 
      - haproxy
    state: present

- name: deploy haproxy conf
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: copy ssl cert
  ansible.builtin.copy:
    src: files/snakeoil.pem
    dest: /etc/ssl/snakeoil.pem
    owner: root
    group: root
    mode: '0644'
  when: copy_ssl

- name: restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: yes
    state: restarted
  ignore_errors: True